/***************************************************************************
Include File:     ASCII.H
Purpose:          To define key scan codes
Written By:       Roy Chancellor 
Last Modified:    05-10-1994
Copyright (c), 1994, EF Data Corporation.
****************************************************************************/
/* regular keys...                                                         */
#define ENTER        13
#define ESC          27
#define BACKSPACE    8
#define TAB          9
#define SPACE        32
/* extended keys...                                                        */
#define UP_ARROW     72
#define DOWN_ARROW   80
#define LEFT_ARROW   75
#define RIGHT_ARROW  77
#define EXTENDED_KEY 0
#define F1           59
#define F2           60
#define F3           61
#define F4           62
#define F5           63
#define F6           64
#define F7           65
#define F8           66
#define F9           67
#define F10          68
#define F11          133
#define F12          134
#define PGDN         81
#define PGUP         73
#define HOME         71
#define ALTD         32
#define ALTC      46
#define ALTF1        104
#define ALTF2        105
#define ALTF3        106
#define ALTF4        107
#define ALTF5        108
#define ALTF6        109
#define ALTF7        110
#define ALTF8        111
#define ALTF9        112
#define ALTF10       113
#define DELETE       83
#define INSERT       82
#define END          79
