/***************************************************************************
Include File:		boolean.h
Purpose:				to define values used often that are 1 or 0
Written By:   		Roy Chancellor
Last Modified:		02-23-1994
Copyright (c), 1994, EF Data Corporation.
****************************************************************************/
#define YES          1
#define NO           0
#define TRUE         1
#define FALSE        0
#define ON				1
#define OFF				0
#define OK				1
#define FAIL			0
#define CORRECT		1
#define INCORRECT	0

