/***************************************************************************
Include File:     monvalue.h
Purpose:          function prototype for viewebno function
Written By:       Roy Chancellor 
Last Modified:    04-01-1994
Copyright (c), 1994, EF Data Corporation.
****************************************************************************/
#define EBNO_LFT     5
#define EBNO_TOP     4
#define EBNO_RYT     35
#define EBNO_BOT     9
#define RX_LFT       5
#define RX_TOP       4
#define RX_RYT       35
#define RX_BOT       9
#define ADCI2C_LFT   5
#define ADCI2C_TOP   4
#define ADCI2C_RYT   35
#define ADCI2C_BOT   11

int   monitor_values( char * );
